Add LANG and LC_ALL to the executions
Some languages (e.g. some versions of Python) may behave strangely
without any locale. For example Python tries to encode/decode strings as
they were in ascii instead of the more sensible UTF-8. Therefore, even a
print("à") failed with:

UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in
position 0: ordinal not in range(128)

Remote executions may have installed different locales from the local
client. We set those variables copying the value from the sandbox
executor.